import DOMPurify from 'dompurify';

/**
 * Sanitize untrusted HTML generated by AI using DOMPurify.
 * Prevents XSS script injections.
 * @param {string} dirty - Dirty HTML string
 * @returns {string} - Clean sanitized HTML
 */
export const sanitizeHTML = (dirty) => {
  if (!dirty) return '';
  return DOMPurify.sanitize(dirty, {
    ALLOWED_TAGS: [
      'p', 'b', 'i', 'em', 'strong', 'a', 'ul', 'ol', 'li', 'code', 'pre', 
      'span', 'h1', 'h2', 'h3', 'h4', 'br', 'hr', 'div', 'table', 'thead', 
      'tbody', 'tr', 'th', 'td'
    ],
    ALLOWED_ATTR: ['href', 'target', 'class', 'style', 'rel'],
    ADD_ATTR: ['target'],
    FORCE_BODY: true
  });
};

/**
 * Client side YouTube URL regex validator.
 * @param {string} url - User URL input
 * @returns {boolean} - Matches format
 */
export const validateYouTubeURL = (url) => {
  if (!url) return false;
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
  const match = url.match(regExp);
  return (match && match[2].length === 11);
};
